export const professionRoleOptions = ['Front-end', 'Back-end', 'Fullstack', 'Mobile', 'DevOps', 'UX/UI', 'QA', 'Gestão', 'Product Manager', 'Product Owner', 'Agile Coach', 'Scrum Master', 'Data Science', 'Business Intelligence'];

export const technologiesOptions = [
  'React.js',
  'Vue.js',
  'Angular.js',
  'Node.js',
  'Nest.js',
  'Express.js',
  'Laravel',
  'Symfony',
  'Django',
  'Flask',
  'Spring',
  'Ruby on Rails',
  'ASP.NET',
  'ASP.NET Core',
  'Java',
  'JavaFX',
  'Python',
  'Go',
  'Rust',
  'Swift',
  'Typescript',
  'Javascript',
  'Python',
  'Docker',
  'Kubernetes',
  'Kafka',
  'RabbitMQ',
  'Redis',
  'Postgres',
  'MongoDB',
  'FaunaDB',
  'Cassandra',
  'Elasticsearch',
  'Firebase',
  'AWS',
  'Azure',
  'Google Cloud',
  'Heroku',
  'Digital Ocean',
  'Netlify',
  'Vercel',
  'Git',
  'Github',
  'Gitlab',
  'Bitbucket',
  'Jenkins',
  'CircleCI',
  'TravisCI',
  'Jest',
  'Mocha',
  'Cypress',
  'Selenium',
  'Puppeteer',
  'JUnit',
  'Jasmine',
  'Karma',
  'Flutter',
  'React Native',
  'Ionic',
  'Xamarin',
  'SwiftUI',
  'Android',
  'iOS',
  'Windows',
  'Linux',
  'MacOS',
  'Arduino',
  'Raspberry Pi',
  'Unity',
  'Unreal Engine',
  'Blender',
  'Photoshop',
  'Illustrator',
  'Figma',
  'Adobe XD',
  'Sketch',
  'Invision',
  'Zeplin',
  'Marvel',
  'Framer',
  'Principle',
  'Abstract',
  'Framer Motion',
  'Material UI',
  'Bootstrap',
  'Tailwind CSS',
  'Styled Components',
  'SASS',
  'LESS',
  'CSS Modules',
  'CSS Grid',
  'CSS Flexbox',
  'HTML',
  'HTML5',
  'Web Components',
  'Web Assembly',
  'WebGL',
  'Canvas',
  'SVG',
  'D3.js',
  'Three.js',
  'Next.js',
  'Nuxt.js',
  'Gatsby',
  'Gridsome',
  'React Router',
  'Vue Router',
  'React Query',
  'Axios',
  'Apollo Client',
  'GraphQL',
  'Redux',
  'MobX',
  'Vuex',
  'React Hook Form',
  'Formik',
  'Yup',
  'Joi',
  'React Testing Library',
  ]