export const metadata = {
  title: 'Portfolio Dev',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="w-screen h-screen bg-gradient-to-r from-gray to-black">
      {children}
    </div>
  )
}
