import './globals.css';

export const metadata = {
  title: 'Portfolio Dev',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className="font-montserrat">{children}</body>
    </html>
  );
}
